## Test the nex reader.
## 2014-03-17
## test1.nex is generated by the matlab script
## ~/langs/matlab/matpath/neuroexplorer/exampleSaveDataInNexFile.m

context("Check test1.nex")

x = nexread(system.file("examples", "test1.nex", package="sjemea"))
expect_equal(x$nvar, 5)

context("Check reading a nex file against a timestamp file")






